language: ruby
rvm:
  - 2.2.2
  - 2.1.6
before_install:
  - sudo apt-add-repository -y ppa:beineri/opt-qt541
  - sudo apt-get update
  - sudo apt-get install -y qt54base qt54declarative
before_script:
  - source /opt/qt54/bin/qt54-env.sh
  - cd ext/qml
  - bundle exec ruby extconf.rb
  - make
